### ISSUE TITLE
Better accommodate RP times

### ISSUE THREAD

**Issue by Sorrieah** [Tyxz/Clock-Tamriel-Standard-Time#6]
**Is your feature request related to a problem? Please describe.**
In my RP guild, we use a variation of the year that begins with the year of ESO's launch (2014) tied to the beginning lore year of the game (2E582). With this definition of year, the current fake lore year for all our RP is 2E588, but there's no way to see that reflected in the clock. Additionally, events are run based on EST, which I understand to be server time, but the addon only seems to read my local computer time (which is 15 hours ahead of EST and therefore confuses even the weekdays for 90% of my RP).

I don't know what other RP groups use, but I can only assume there are people with similar problems.

**Describe the solution you'd like**
I would like to be able to designate the year in a way that it would display our RP year appropriately in both the main view of the clock and the tooltip. I would also like to be able to set the timezone to EST to keep track of guild event times by their lore time and date.

**Describe alternatives you've considered**
I've set the year manually by just entering 2E588 in the text window, but it still shows either the real or fake lore year in the tooltip (since they're the same I don't know which one).

**Comment by Tyxz** [comment]
Thank you for your feedback.

Right now, the tooltip is hard coded, but I can change this to be in the same format as I use for the clock.

It is also possible to include a "years since start" option to display the lore year as 2E588. As it is, the year is calculated by how many days have past. And you are right: The lore year is the same as the fake lore year.

Your last point is a bit more complicated. I don't have access to the whole Lua functionality and have to use what Zenimax is giving me. For instance, I can't access your local timezone, as far as I know. What I have access to is a function which "returns the current Unix time in seconds in UTC based on the player's OS time." This one I use for all lore calculations. Therefore, the lore date and time should be UTC based and everywhere the same. Only the "fake lore" date is based on your local OS time. 
I can look further into this point, but I guess the easiest solution would be for you to change your OS time settings to EST as my fake lore and real date functions are based on your OS.
